"""Fan-facing comparison, with explicit scopes and progressive enhancement."""
import html
from pathlib import Path
from render_fan_report import table
ROOT=Path(__file__).resolve().parents[1]
MODES=('rated','casual')
BOTS=('maia1','maia5','maia9')
COLOR={'rated':'#a16c4d','casual':'#457b5c'}
def n(x): return f'{x:,}'
def p(x,d): return 100*x/d if d else 0
def esc(x): return html.escape(str(x))
def bot(x): return x.replace('maia','Maia ')
def legend(): return '<div class="legend"><span><i style="background:#a16c4d"></i>Rated</span><span><i style="background:#457b5c"></i>Casual</span></div>'
def pair(title, rated, casual, subtitle='Share of each format · 0–100% scale'):
    return f'<div class="pair"><h3>{esc(title)}</h3>'+''.join(f'<div class="pair-row"><span>{mode.title()}</span><div class="pair-track"><i style="width:{v:.4f}%;background:{COLOR[mode]}"></i></div><b>{v:.1f}%</b></div>' for mode,v in [('rated',rated),('casual',casual)])+f'<p class="small">{subtitle}</p></div>'
def chart(months, remove=0):
    W,H,L,T,P=1000,310,60,20,230;high=120000;step=915/(len(months)-1)
    out=['<svg viewBox="0 0 1000 310" role="img" aria-label="Monthly rated and casual games. Full values are in the expandable table below.">']
    for v in range(0,120001,30000):
        y=T+P-v/high*P
        out.append(f'<path d="M{L} {y}H980" stroke="#d0d9cc"/><text x="{L-10}" y="{y+4}" text-anchor="end">{v//1000}k</text>')
    for mode in MODES:
        vals=[m[mode]-(remove if mode=='casual' and j==len(months)-1 else 0) for j,m in enumerate(months)]
        points=' '.join(f'{L+j*step:.1f},{T+P-v/high*P:.1f}' for j,v in enumerate(vals))
        out.append(f'<polyline points="{points}" fill="none" stroke="{COLOR[mode]}" stroke-width="3"/>')
        for j,v in enumerate(vals):
            out.append(f'<circle cx="{L+j*step:.1f}" cy="{T+P-v/high*P:.1f}" r="3" fill="{COLOR[mode]}"><title>{months[j]["month"]} {mode}: {n(v)}</title></circle>')
    for j in [0,8,14,20,26,34]:
        out.append(f'<text x="{L+j*step:.1f}" y="285" text-anchor="middle">{months[j]["month"]}</text>')
    return ''.join(out)+'</svg>'
def outcome_panel(data,key):
    result='<div class="outcome-cards">'
    for b in BOTS:
        rs=next(x for x in data['rated'][key] if x['bot']==b);cs=next(x for x in data['casual'][key] if x['bot']==b)
        result+=pair(bot(b),p(rs['win'],rs['games']),p(cs['win'],cs['games']),f'Maia wins / all games · rated n={n(rs["games"])}; casual n={n(cs["games"])}')
    result+='</div>'
    rows=[]
    for b in BOTS:
        for mode in MODES:
            x=next(x for x in data[mode][key] if x['bot']==b)
            rows.append((bot(b),mode.title(),n(x['games']),*[f'{p(x[k],x["games"]):.1f}%' for k in ('win','draw','loss','unknown')]))
    return result+table(['Maia','Format','Games','Maia wins','Draws','Maia loses','Unknown'],rows)

def render(d,b):
    r,c=d['rated'],d['casual'];total=d['combined_unique_games'];over=d['account_overlap'];union=sum(over.values());out=d['september_2026_concentration'];sensitivity=b['outlier_sensitivity'];matched=b['matched_standard_outcomes'];regular=b['shared_regular_accounts_standard']
    growth=lambda x:100*(x['last_12_complete_months']/x['first_12_complete_months']-1)
    mode=b['modes'];custom=c['variant'].get('fromPosition',0)
    favorite=''.join(pair(bot(botid),p(r['per_bot'][botid],r['unique_games']),p(c['per_bot'][botid],c['unique_games'])) for botid in BOTS)
    speeds=''.join(pair(speed.title(),p(r['speed'].get(speed,0),r['unique_games']),p(c['speed'].get(speed,0),c['unique_games'])) for speed in ('rapid','blitz','classical','bullet'))
    all_shared={x['mode']:x for x in regular['rates'] if x['prior_outcome']=='all'}
    after={ (x['mode'],x['prior_outcome']):x for x in regular['rates']}
    returns=pair('The same returning accounts',all_shared['rated']['account_equal_pct'],all_shared['casual']['account_equal_pct'],'Each account counts equally · return to any Maia, either format')
    returntable=table(['Previous game','Rated','Casual'],[(name,f'{after["rated",key]["account_equal_pct"]:.1f}%',f'{after["casual",key]["account_equal_pct"]:.1f}%') for key,name in [('all','Any outcome'),('win','Opponent won'),('loss','Opponent lost')]])
    quick={m:{k:sum(x[k] for x in b['quick_returns_standard'] if x['mode']==m) for k in ('eligible_games','quick_any_mode','quick_same_mode','quick_other_mode')} for m in MODES}
    quicktable=table(['Prior format','Eligible games','Quick returns','Same format','Other format'],[(m.title(),n(quick[m]['eligible_games']),n(quick[m]['quick_any_mode']),n(quick[m]['quick_same_mode']),n(quick[m]['quick_other_mode'])) for m in MODES])
    switch_pct={m:p(quick[m]['quick_other_mode'],quick[m]['quick_any_mode']) for m in MODES}
    account_table=table(['Habit','Rated','Casual'],[('Accounts observed',n(r['opposing_accounts']),n(c['opposing_accounts'])),('Exactly one observed game',f'{mode["rated"]["one_game_accounts_pct"]:.1f}%',f'{mode["casual"]["one_game_accounts_pct"]:.1f}%'),('Median games per account',f'{mode["rated"]["median_games_per_account"]:g}',f'{mode["casual"]["median_games_per_account"]:g}'),('Games from busiest 1% of accounts',f'{p(mode["rated"]["top_1pct_games"],r["unique_games"]):.1f}%',f'{p(mode["casual"]["top_1pct_games"],c["unique_games"]):.1f}%')])
    overlap_graph=''.join(f'<div style="flex:{count};background:{color}"><b>{n(count)}</b><span>{name}</span></div>' for count,name,color in [(over['casual_only'],'Casual only','#c7ddc2'),(over['both'],'Both','#e2cf9d'),(over['rated_only'],'Rated only','#dfc5b2')])
    clocks=table(['Rank','Rated clock','Rated share','Casual clock','Casual share'],[(i+1,r['top_controls'][i]['label'],f'{p(r["top_controls"][i]["games"],r["unique_games"]):.1f}%',c['top_controls'][i]['label'],f'{p(c["top_controls"][i]["games"],c["unique_games"]):.1f}%') for i in range(5)])
    monthtable=table(['UTC month','Rated games','Casual games','Rated accounts','Casual accounts'],[(x['month'],n(x['rated']),n(x['casual']),n(x['rated_accounts']),n(x['casual_accounts'])) for x in d['monthly_complete']])
    methods=table(['Check','Rated','Casual'],[('Records',n(r['unique_games']),n(c['unique_games'])),('Standard variant tag',n(r['variant'].get('standard',0)),n(c['variant'].get('standard',0))),('fromPosition variant tag',n(r['variant'].get('fromPosition',0)),n(custom)),('Missing account handles',n(r['missing_opponent_ids']),n(c['missing_opponent_ids']))])
    delta=matched['mean_casual_minus_rated_pp'];direction='lower' if delta<0 else 'higher'
    outcomes=outcome_panel(d,'outcomes_standard');alloutcomes=outcome_panel(d,'outcomes_all_games')
    body=f'''<a class="skip" href="#report">Skip to supplement</a><header class="masthead"><a class="brand" href="index.html"><span aria-hidden="true">♞</span> MAIA / FIELD NOTES</a><nav aria-label="Supplement sections"><a href="#habits">Habits</a><a href="#returns">Play again</a><a href="#outcomes">Results</a><a href="#methods">Data</a></nav><a class="download" href="20261008_v0_maia_casual_comparison.pdf">Download PDF ↗</a></header><main id="report">
<section class="supp-hero"><div><p class="eyebrow">Casual × rated / Supplement · October 2026</p><h1>Same Maia.<br><em>Two ways to play.</em></h1><p class="dek">When rating points are off the table, what changes? A look at shared habits, quick returns and results across <b>{total/1e6:.2f} million</b> collected games.</p><p class="small">Companion to <a href="index.html">One more game with Maia</a>. Same three bots, same three-year last-move window. All-time profile totals are a separate snapshot.</p></div><div class="format-cards"><article><p class="eyebrow">Casual</p><strong>{c['unique_games']/1e6:.2f}<small>million</small></strong><p>{p(c['unique_games'],total):.1f}% of collected games</p><span>Rating points off the table</span></article><article><p class="eyebrow">Rated</p><strong>{r['unique_games']/1e6:.2f}<small>million</small></strong><p>{p(r['unique_games'],total):.1f}% of collected games</p><span>Rating points in play</span></article></div></section>
<div class="scope-strip"><span class="live-dot"></span><p><b>One important difference:</b> {n(custom)} casual games ({p(custom,c['unique_games']):.1f}%) are tagged <code>fromPosition</code>. All rated games are tagged <code>standard</code>. We separate these when comparing results and repeat play; exact starting positions were not saved.</p></div>
<section class="section" id="habits"><p class="eyebrow">01 / What stays familiar</p><h2>The favorites barely change.</h2><p class="body-large">Maia 1 attracts almost the same share in each format: <b>{p(c['per_bot']['maia1'],c['unique_games']):.1f}% casual</b> and <b>{p(r['per_bot']['maia1'],r['unique_games']):.1f}% rated</b>. And 10+0 is the most popular exact clock in both.</p>{legend()}<div class="three-col">{favorite}</div><div class="two-col pattern-bottom"><div><h3>A little more slow chess in casual.</h3><p>Rapid and classical together account for {p(c['speed'].get('rapid',0)+c['speed'].get('classical',0),c['unique_games']):.1f}% of casual games, versus {p(r['speed'].get('rapid',0)+r['speed'].get('classical',0),r['unique_games']):.1f}% of rated games. Those are game-weighted shares, so very active accounts matter.</p><div class="speed-grid">{speeds}</div></div><div><h3>The same top three clocks.</h3>{clocks}<p class="small">Starting minutes + increment seconds. These preference comparisons include all collected games, including custom-start records. Share denominators are all games in each format.</p><div class="callout"><b>Watch the 1+0 ranking.</b> One account contributes {n(out['one_plus_zero_games'])} casual 1+0 games in September alone. That is {p(out['one_plus_zero_games'],next(x['games'] for x in c['top_controls'] if x['label']=='1+0')):.1f}% of casual 1+0 games in the whole collection. Remove that account’s games and 1+0 falls from fourth to seventh; casual bullet’s share falls from 12.0% to 9.2%.</div></div></div></section>
<section class="section" id="accounts"><p class="eyebrow">02 / Two crowds, with an overlap</p><h2>A bigger casual audience.<br>A familiar pattern of regulars.</h2><p class="body-large">We see {n(c['opposing_accounts'])} casual accounts and {n(r['opposing_accounts'])} rated accounts. Only <b>{p(over['both'],union):.1f}% of the {n(union)} distinct observed handles</b> appear in both formats.</p><figure class="overlap"><div>{overlap_graph}</div><figcaption>Distinct handles in this window. “Only” means only observed in that format here, not a lifetime preference. Accounts are not necessarily distinct people.</figcaption></figure><div class="two-col"><div><h3>Many visitors. A very active core.</h3><p>In both formats, roughly four in ten accounts appear just once. Yet just 1% of accounts contribute more than half the games. Casual play has the larger observed audience; neither format is evenly spread across its accounts.</p><p class="small">Top 1% is chosen separately for each format, with the number of accounts rounded to the nearest whole account. Anonymous games stay in total-game denominators but cannot enter account counts.</p></div><div>{account_table}</div></div></section>
<section class="section returns-section" id="returns"><p class="eyebrow">03 / The next game</p><h2>Same regulars.<br>Almost identical return rates.</h2><p class="body-large">Both formats have a <b>50.6% quick-return rate</b> when each qualifying account counts equally. We follow the next observed Maia game across <b>both</b> formats. To reduce the effect of different audiences, this comparison uses {n(regular['accounts'])} accounts with at least ten eligible standard-start games in each format.</p><div class="two-col"><div>{returns}<p class="small">A quick return starts within ten minutes of the previous last recorded move. Each eligible prior game stays in the denominator, even if no later game is observed.</p></div><div><h3>What follows a win or a loss?</h3>{returntable}<p class="small">Opponent’s result in the prior game. For each row, average each qualifying account’s return rate equally; outcome-specific rows include only accounts with that outcome. This describes return behavior, not motivation.</p></div></div><div class="callout"><b>Most quick returns stay in the same format.</b> Across eligible standard-start games, {100-switch_pct['rated']:.1f}% of quick returns after rated games are rated again; {100-switch_pct['casual']:.1f}% after casual games are casual again. This uses all identified accounts, so it is a different population from the equal-account comparison above.</div><details><summary>Return counts, weighting and observation limits</summary>{quicktable}<p>Only a standard-tagged prior game followed immediately in the observed sequence by a standard-tagged game can count as a standard quick return. Intervening <code>fromPosition</code> games are never skipped. The next game may involve any of the three Maia bots.</p><p>Prior games need an identified account, nonnegative recorded duration and at least ten minutes remaining before the export ends. Last-move time can precede resignation or flagging. We cannot see games against other opponents, private activity, or games outside this window. This is not a formal rematch count.</p><p>In this same selected cohort, game-weighted rates are rated {all_shared['rated']['game_weighted_pct']:.1f}% and casual {all_shared['casual']['game_weighted_pct']:.1f}%. Frequent accounts have more influence in those rates.</p></details></section>
<section class="section outcomes-section" id="outcomes"><p class="eyebrow">04 / Same bot, different results</p><h2>Separate the starting position.<br>Then compare the opponents.</h2><p>Raw casual and rated results mix different accounts, clocks and starting positions. Below, <b>standard-tagged games</b> are the default. Win percentages use <b>all games</b>, including draws and unknown outcomes, so they match the definition in the original report.</p><div class="filter" role="group" aria-label="Outcome scope" data-filter-group="outcomes"><button type="button" data-panel="standard-outcomes" aria-controls="standard-outcomes" aria-pressed="true">Standard-tagged games</button><button type="button" data-panel="all-outcomes" aria-controls="all-outcomes" aria-pressed="false">All collected games</button></div><div id="standard-outcomes" data-group="outcomes">{outcomes}</div><div id="all-outcomes" data-group="outcomes" hidden>{alloutcomes}</div><p class="small">Bot perspective. A white/black winner determines win or loss; a blank winner is a draw only for explicit draw/stalemate status, otherwise unknown. Full-collection tables retain recorded cheat terminations; the matched comparison below excludes them.</p><div class="matched"><h3>What if we compare the same accounts?</h3><div class="two-col"><div>{pair(f'{n(matched["accounts"])} matched accounts',matched['mean_rated_score_pct'],matched['mean_casual_score_pct'],'Opponent score · win = 1, draw = ½, loss = 0')}</div><div><p>For each account, match the <b>same Maia, exact clock, speed category and color</b>, with at least ten known-outcome standard games in each format. Give each selected account equal weight.</p><p>Average opponent score is <b>{abs(delta):.1f} percentage points {direction} in casual</b> in this selected group. This is an association, not the effect of turning rating points on or off.</p></div></div><p class="small">One qualifying combination per account, selected by the largest smaller-format game count, then total games. Games need not be contemporaneous: the median absolute gap between the two formats’ mean start dates is {matched['median_absolute_mean_created_gap_days']:.0f} days. Outside practice, changes over time, and format choice can still explain differences. This is not an early/later improvement study.</p><details><summary>Matched sample and per-Maia results</summary>{table(['Maia','Accounts','Casual − rated score'],[(bot(x['bot']),n(x['accounts']),f'{x["mean_casual_minus_rated_pp"]:+.1f} pp') for x in matched['by_bot']])}<p>Selected games: {n(matched['rated_games'])} rated and {n(matched['casual_games'])} casual. Accounts with higher casual score: {n(matched['casual_score_higher_accounts'])}; equal: {n(matched['same_score_accounts'])}; lower: {n(matched['casual_score_lower_accounts'])}. Unknown outcomes and cheat terminations are excluded. This small persistent subset does not represent all accounts.</p></details></div></section>
<section class="section" id="growth"><p class="eyebrow">05 / More games does not always mean more people</p><h2>Both grew.<br>Rated grew faster.</h2><div class="fact-row growth-facts"><div><b>+{growth(r):.1f}%</b><span>rated games</span></div><div><b>+{growth(c):.1f}%</b><span>casual games</span></div><div><b>+{out['growth_excluding_account_pct']:.1f}%</b><span>casual, excluding one account’s September games</span></div></div><p class="small">Earliest complete 12 months: Nov 2023–Oct 2024. Latest: Oct 2025–Sep 2026. This is not a comparison of consecutive years. Partial October 2023 and October 2026 are excluded. Across these blocks, casual’s share of combined games falls from {p(c["first_12_complete_months"],c["first_12_complete_months"]+r["first_12_complete_months"]):.1f}% to {p(c["last_12_complete_months"],c["last_12_complete_months"]+r["last_12_complete_months"]):.1f}%.</p><div class="filter" role="group" aria-label="Casual growth sensitivity" data-filter-group="trend"><button type="button" data-panel="trend-full" aria-controls="trend-full" aria-pressed="true">All collected games</button><button type="button" data-panel="trend-sensitive" aria-controls="trend-sensitive" aria-pressed="false">Exclude September burst</button></div><figure class="chart"><div id="trend-full" data-group="trend">{legend()}{chart(d['monthly_complete'])}</div><div id="trend-sensitive" data-group="trend" hidden>{legend()}{chart(d['monthly_complete'],out['games'])}</div><figcaption>Monthly games, grouped by last recorded move timestamp. Both views use the same vertical scale.</figcaption></figure><div class="callout"><b>One account, {n(out['games'])} September games.</b> That is {out['share_of_september_pct']:.1f}% of the month’s casual volume. Excluding only those games leaves {n(out['september_without_account'])} casual September games, versus {n(out['august_games'])} in August. Meanwhile, casual active accounts went from {n(out['august_accounts'])} in August to {n(out['september_accounts'])} in September. The volume spike is not a surge in account numbers.</div><p class="small">The sensitivity view retains that account’s other months and all other games. It is a concentration check, not a claim about its identity, motives or legitimacy. We have not verified that every opposing account is human.</p><details><summary>Every complete month and the sensitivity definitions</summary>{monthtable}<p>The trend sensitivity excludes only the largest September account’s {n(out['games'])} casual games in that month. A separate clock/speed sensitivity in the <a href="data/comparison_behaviour.json">behavior JSON</a> removes all {n(sensitivity['top_account_full_window_casual_games'])} casual games from that account across the full window. These are different exclusions.</p></details></section>
<section class="section methods" id="methods"><p class="eyebrow">06 / What this comparison can tell us</p><h2>Shared habits.<br>Different contexts.</h2><div class="method-grid"><article><h3>Similarities</h3><p>The same most-played Maia, the same top three clocks, many one-game visitors and a small core producing most of the games. Those patterns recur in both formats.</p></article><article><h3>Differences</h3><p>A larger casual audience, limited observed overlap, somewhat more slow chess, and different results—even within a selected matched group. The raw format averages alone do not explain why.</p></article><article><h3>What remains unanswered</h3><p>Whether one format improves chess skill more. These metadata contain no moves or evaluations, and the choice of format is not randomized. The original rated early/later analysis remains a separate question.</p></article></div>{methods}<p class="small">Frozen observed exports: last recorded move at or after 4 Oct 2023 00:00 UTC and before 4 Oct 2026 09:00 UTC. All {n(total)} IDs are unique across the published corpora. Verification covers hashes, sizes, rows, IDs and timestamps; public files cannot independently prove API completeness. Casual collection used a seven-day creation-time lookback; longer boundary-crossing games can still be missed. Recorded Lichess ratings mix speed-specific pools and are not a clean casual skill measure.</p><div class="data-links"><a href="data/comparison_behaviour.json">Behavior & matched results · JSON ↗</a><a href="data/casual_comparison.json">Comparison aggregates · JSON ↗</a><a href="data/casual_comparison_monthly.csv">Monthly data · CSV ↗</a><a href="https://github.com/Dash1971/researching-maia-games-on-lichess/tree/main/data/casual-games">Casual records & field guide ↗</a><a href="https://github.com/Dash1971/researching-maia-games-on-lichess/blob/main/RESEARCH_PLAN.md">Methods ↗</a></div><p class="small">Source: <a href="https://lichess.org/api#operation/apiGamesUser">Lichess user-game export</a>. No moves, FENs, PGNs, chat, credentials or private identity mappings are included. Independent fan research, not an official Maia or Lichess publication. The MIT license covers original writing and code, not a relicensing of Lichess or player data.</p></section></main><footer><a class="brand" href="index.html">♞ MAIA / FIELD NOTES</a><p>A companion for everyone who plays “just one more.”</p><a href="#report">Back to top ↑</a></footer>'''
    css=(ROOT/'scripts'/'report.css').read_text()+'\n'+(ROOT/'scripts'/'supplement.css').read_text()
    js=(ROOT/'scripts'/'report.js').read_text()
    return '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="How casual and rated Maia play compare: habits, shared accounts, quick returns, matched results and the limits of raw game counts."><title>Same Maia, two ways to play — Casual × rated supplement</title><style>'+css+'</style></head><body>'+body+'<script>'+js+'</script></body></html>\n'
